[phases.setup]
aptPkgs = ["libpq-dev"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[phases.install]
cmds = ["mkdir -p storage/framework/{sessions,views,cache/data}", "composer install --no-dev --optimize-autoloader"]
