[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_pgsql", "php84Extensions.pgsql", "php84Extensions.bcmath", "php84Extensions.zip"]
aptPkgs = ["libpq-dev"]

[phases.install]
cmds = ["mkdir -p storage/framework/{sessions,views,cache/data}", "composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]
